### ISSUE TITLE
Code Arduino Diagnostic Battery Segway

### ISSUE THREAD

**Issue by krafaello** [martinbogo/i2-battery-diagnostics#11]
Hi
I  Would like chceck my battery Segway -secection battery.
I have problem. I write code my Arduino uno but program dont work.
I have LCD 2004 but nothing is displayed. The code is 100% correct?

**Comment by martinbogo** [comment]
Last time I checked, the code compiled and worked.  You can communicate
using the serial menu if you're having issues with the LCD code.

**Comment by krafaello** [comment]
Hi
My port Lcd 2004 is 0x27 
I have Arduino UNO

**Comment by martinbogo** [comment]
Sounds like you can fix the code then, easily.  Good luck!

http://wiki.sunfounder.cc/index.php?title=I2C_LCD2004

**Comment by krafaello** [comment]
Hi 
My LCD is good (positive test).-test code program „hello Word”
When write Code Diagnostic Battery  received „Bushes”.###########.
Serial menu shows good...
What I doping wrong?
You can check again code?
Thanks 
![28CA3AD8-484B-44CA-9FCF-996FBB172FB0](https://user-images.githubusercontent.com/81326366/112730310-2b721b80-8f31-11eb-8020-71d217e10064.jpeg)
![6FA0C809-107A-4D00-93AE-3885E3B63C18](https://user-images.githubusercontent.com/81326366/112730313-30cf6600-8f31-11eb-9526-1e0672454f71.jpeg)
Raf

**Comment by martinbogo** [comment]
I am no longer actively developing this code... I'm afraid I don't have the
time to debug your issue.  Sorry.
