### ISSUE TITLE
SoC

### ISSUE THREAD

**Issue by JorgeTorres01** [martinbogo/i2-battery-diagnostics#13]
Hi 
I can read data from the battery. 
But the SoC "c" is showing 0,39 %. 
I test with 3 different batteries and this value is the same (2 batteries with voltage pack 76 - 78 V and another BMS with dead cell / without cells).

@martinbogo did you get SoC values correct? 

With logic analyser the response to command 0x1D (SoC rigth ?) is : 0x65  0xFF 0xFE

Thank you @martinbogo

**Comment by martinbogo** [comment]
Hi Jorge,

I have ceased work on this codebase as Segway no longer produces the PT.   If you have a correction to the code, I will fold it in.  It sounds like the batteries you are using have a different revision and/or response structure... but I don't have any batteries left to test with to check your issue.

I'm afraid I have no real choice but to close this issue... 

Sincerely,
Martin
