### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Migu5499** [martinbogo/i2-battery-diagnostics#6]
Hi idk how thia project works, i just want to build a segway battery diagnostic that tell me if cells are good enough, there is a list of materials and processes i have to do to build it??.
Thank for your work, hope we can talk!

**Comment by martinbogo** [comment]
Migu...

This is code that I wrote to document and help people understand the Segway
I2 lithium battery BMS responses.

It's useful, but not meant to be a product... just a guide and a learning
tool.

To use the tool you're going to need an Arduino, and some electronics
engineering skis and confidence working around high voltage (70v)
batteries.  You can seriously hurt yourself and damage your equipment.

**Comment by Migu5499** [comment]
Nice thank you for your fast reply, im a e-scooter fixer so i have knowledge about high voltage, but im a little noob building this things but sure i want to try build a segway battery checker!!
