### ISSUE TITLE
Displaying battery data without i2c Lcd 

### ISSUE THREAD

**Issue by Moejaahied** [martinbogo/i2-battery-diagnostics#7]
Hi Martin,

I'm a Arduino newb, living in Cape Town, South Africa, with an electrical and electronics background. 

Have acquired all the hardware and software except the 20 x 4 i2c lcd display. Will order the display today. Have installed the Arduino IDE software for windows and downloaded the Github zipped file. Loaded the ino file onto the Arduino Uno.

Hardware:

Arduino Uno board.

12v Dc transformer to provide 12v to battery enable

All leads/wires from Uno to battery have be prepared and connected, with labels to the pins on Uno and battery sides.

Will connect the 20 x 4 i2c LCD display to the 5v supply leads and SCL and SDA pins on the Uno.

Until the display arrives is there any way to display the voltages, temps, state of charge and Serial number on my laptop?

Hope you can assist.

Regards

Moejaahied Bardien

**Comment by martinbogo** [comment]
By default, the code displays everything on a serial port.
